name: Issue triage
on:
  issues:
    types: [opened, labeled]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          triageLabel: 'S: triage'
          sponsorsFile: '.github/sponsors.yml'
          triagedLabels: |-
            T: documentation
            T: bug
            T: enhancement
            T: feature
            T: question
